DATASET:
  root_dataset: "../AD/data/camvid_all/CamVid/"
  list_train: "data/new_train.odgt"
  list_val: "data/new_val.odgt"
  num_class: 150
  imgSizes: (720, 960)
  imgMaxSize: 1000
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "resnet50"
  arch_decoder: "multi-uper"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 1
  num_epoch: 60
  start_epoch: 30
  epoch_iters: 400
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 1
  disp_iter: 20
  seed: 304
 
VAL:
  visualize: False
  checkpoint: "epoch_30.pth"

TEST:
  checkpoint: "epoch_30.pth"
  result: "./"

DIR: "ckpt/kd"

